### ISSUE TITLE
Cannot place Auxiliary Electronic Navigatior if Breaking Ground is not installed

### ISSUE THREAD

**Issue by Alex-1248** [Angel-125/Buffalo2#6]
If Breaking Ground DLC is not instaled, when I click the Auxiliary Electronic Navigatior icon in VAB, this part does not appear. I opened the b2AuXEN.cfg file, removed the ModuleRoboticController module and after that the problem disappeared.

**Comment by Angel-125** [comment]
Fixed in latest release, thanks!
